name: mza-validation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - shapely
  - geopandas
  - pyproj
  - lxml
  - networkx
  - pillow
  - scipy
  - scikit-learn
  - scikit-image
  - pyyaml
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - torch
